on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Publish
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
      - name: Build Wheel
        run: |
          python setup.py sdist
      - name: Publish to PyPI
        run: |
          echo "[pypi]
          username = __token__
          password = $PYPI_TOKEN" > ~/.pypirc

          python -m twine upload --repository pypi dist/*
